# Generated by Django 2.0.2 on 2018-02-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='agency',
            field=models.CharField(blank=True, max_length=50, verbose_name='기힉사'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=100, verbose_name='장르'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_company',
            field=models.CharField(blank=True, max_length=50, verbose_name='발매사'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='발매일'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, verbose_name='앨범명'),
        ),
    ]
