# Generated by Django 2.0.2 on 2018-02-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180208_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='가수'),
        ),
    ]
