# Generated by Django 2.0.2 on 2018-02-21 14:27

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_album_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to=album.models.dynamic_album_cover_path, verbose_name='커버 이미지'),
        ),
    ]
