# Generated by Django 2.0.2 on 2018-02-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20180207_1107'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_date', models.DateTimeField(null=True)),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(through='song.ArtistSong', to='artist.Artist'),
        ),
    ]
