# Generated by Django 2.0.2 on 2018-02-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20180208_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='arranging',
        ),
        migrations.RemoveField(
            model_name='song',
            name='composing',
        ),
        migrations.RemoveField(
            model_name='song',
            name='flac',
        ),
        migrations.RemoveField(
            model_name='song',
            name='writing',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='곡 제목'),
        ),
    ]
