# Generated by Django 2.0.2 on 2018-02-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20180208_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
