# Generated by Django 2.0.2 on 2018-02-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_auto_20180208_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistsong',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistsong',
            name='song',
        ),
        migrations.DeleteModel(
            name='ArtistSong',
        ),
    ]
