# Generated by Django 2.0.2 on 2018-02-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_auto_20180208_1348'),
        ('song', '0010_auto_20180208_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='가수'),
        ),
    ]
