# Generated by Django 2.0.2 on 2018-02-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0012_remove_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
