# Generated by Django 2.0.2 on 2018-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('a', 'A형'), ('b', 'B형'), ('o', 'O형'), ('c', 'AB형'), ('x', '기타')], max_length=1, verbose_name='혈액형'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='국적'),
        ),
    ]
