# Generated by Django 2.0.2 on 2018-02-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20180207_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='agency',
            field=models.CharField(blank=True, max_length=50, verbose_name='소속사'),
        ),
    ]
