# Generated by Django 2.0.2 on 2018-02-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='agency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='소속사'),
        ),
    ]
