# Generated by Django 2.0.2 on 2018-02-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='member',
        ),
    ]
