# Generated by Django 2.0.2 on 2018-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20180217_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 Artist ID'),
        ),
    ]
