# Generated by Django 2.0.2 on 2018-02-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_artist_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_id',
            new_name='melon_id',
        ),
    ]
